version: '3.8'

services:
  backend:
    build: ./backend
    container_name: exoseek-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/models:/app/models
    environment:
      - ALLOW_ORIGINS=http://localhost:3000,http://localhost:5173
  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:8000
    container_name: exoseek-frontend
    ports:
      - "3000:80" 
    depends_on:
      - backend